### ISSUE TITLE
Sauvegarder le nom dans une BDD SQLite

### ISSUE THREAD

**Issue by sibille-hearc** [mirkomu/SportHallBooking#3]
Ou autre moyen de persistance local

**Comment by mirkomu** [comment]
J'ai un problème pour enregistre les données dans la base local, le code est dans la branche SQLITEv2. 
Je faite la mettez pas sur le master pour l'instant comme elle marche pas.

**Comment by mirkomu** [comment]
J'ai créer un autre projet Android et le avec le code identique (+ -).
 La classe DBOpenHelper est  identique et le code de MaineActivity me semble correct.

le fichier build de gradle est aussi identique (+ -) sauf plugin google-services, mais je pense pas que ce soit liée a cela.


si qqun a une idée pour débuger ce truc

**Comment by mirkomu** [comment]
OK,  c'est résolut j'ai simplement dû désinstaller l'application sur le téléphone.
Et maintenant ça marche.

Donc si vous avez des comportement bizarre en testant votre code je vous conseille de supprimer l'application, ça peut éventuellement résoudre le problème
