### ISSUE TITLE
Vérifier les avertissement levés par le compilateur

### ISSUE THREAD

**Issue by sibille-hearc** [mirkomu/SportHallBooking#6]
Actuellement 27 avertissements mais le code fonctionne. A vérifier si c'est  des choses importantes ou pas et corriger si nécessaire.

**Comment by CyrilWuthrich** [comment]
Les avertissements sont corrigés. Il en reste 4 ! Risque de créer un Null-Pointer Exception mais géré par un bloc try-catch.
